# Generated by Django 2.1.5 on 2020-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pizza_types',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza_types',
            name='name',
            field=models.CharField(blank=True, choices=[('MEET', 'M'), ('CHICKEN', 'CH'), ('MIXCHEESE', 'MIX')], max_length=10, null=True),
        ),
    ]
