# Generated by Django 2.1.5 on 2020-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0004_auto_20200112_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizzas_size',
            field=models.CharField(blank=True, choices=[('MEDIUM', 'M'), ('LARGE', 'L')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pizza_types',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
        migrations.RemoveField(
            model_name='pizza_types',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza_types',
            name='size',
            field=models.CharField(blank=True, choices=[('MEDIUM', 'M'), ('LARGE', 'L')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Pizza_Sizes',
        ),
    ]
