# Generated by Django 2.1.5 on 2020-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0005_auto_20200112_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('MEDIUM', 'M'), ('LARGE', 'L')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas_size',
        ),
        migrations.RemoveField(
            model_name='pizza_types',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza_types',
            name='size',
            field=models.ManyToManyField(to='pizzaorders.Pizza_Sizes'),
        ),
    ]
