# Generated by Django 2.1.5 on 2020-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0006_auto_20200112_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_types',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED')], max_length=10, null=True),
        ),
    ]
