# Generated by Django 2.1.5 on 2020-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0008_auto_20200113_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_types',
            name='name',
            field=models.CharField(blank=True, choices=[('MEET', 'M'), ('CHICKEN', 'CH'), ('MIXCHEESE', 'MIX')], max_length=10, null=True),
        ),
    ]
