# Generated by Django 2.1.5 on 2020-01-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorders', '0009_auto_20200113_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(blank=True, choices=[('MEDIUM', 'M'), ('LARGE', 'L')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza_types',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza_types',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza_types',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pizza_sizes',
            name='Pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaorders.Pizza_Types'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas_size',
            field=models.ManyToManyField(to='pizzaorders.Pizza_Sizes'),
        ),
    ]
